// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB9chEsfgKS7YpiC4q4VY5U8lHJaIEl9o',
    appId: '1:218555567434:web:6c002e016b1930772dc5b3',
    messagingSenderId: '218555567434',
    projectId: 'babynest-bc2f2',
    authDomain: 'babynest-bc2f2.firebaseapp.com',
    databaseURL: 'https://babynest-bc2f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babynest-bc2f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4E-4i6OugA5GjFE5kGb5Bh8isYrSeO3E',
    appId: '1:218555567434:android:53e99f589ba00d0a2dc5b3',
    messagingSenderId: '218555567434',
    projectId: 'babynest-bc2f2',
    databaseURL: 'https://babynest-bc2f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babynest-bc2f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwhe_HIm1aO3uPzdXNabeWwuBJko6ShZM',
    appId: '1:218555567434:ios:f12f6cb3df3ecd762dc5b3',
    messagingSenderId: '218555567434',
    projectId: 'babynest-bc2f2',
    databaseURL: 'https://babynest-bc2f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babynest-bc2f2.firebasestorage.app',
    iosBundleId: 'com.fox.babyNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwhe_HIm1aO3uPzdXNabeWwuBJko6ShZM',
    appId: '1:218555567434:ios:f12f6cb3df3ecd762dc5b3',
    messagingSenderId: '218555567434',
    projectId: 'babynest-bc2f2',
    databaseURL: 'https://babynest-bc2f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babynest-bc2f2.firebasestorage.app',
    iosBundleId: 'com.fox.babyNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB9chEsfgKS7YpiC4q4VY5U8lHJaIEl9o',
    appId: '1:218555567434:web:e1c59cd9ea7ea0922dc5b3',
    messagingSenderId: '218555567434',
    projectId: 'babynest-bc2f2',
    authDomain: 'babynest-bc2f2.firebaseapp.com',
    databaseURL: 'https://babynest-bc2f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babynest-bc2f2.firebasestorage.app',
  );

}